version: '2'
services:
  ner:
    image: gswyhq/ner:bilstm_20190916_2136
#    build: .
    tty: true
    working_dir: "/ner"
    restart: always
    ports:
      - "18000:8000"
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      TZ: CST-8

#    volumes:
#      - .log:/ner/log

    networks:
      - mynet
    command: /ner/docker-entrypoint.sh

networks:
  mynet:
    driver: bridge


# ubuntu@ip-172-33-3-123:~/nlp/_kf_3$ docker-compose -f docker-compose--kf-20180830.yml --project-directory /ner up -d
# 查看容器
# gswyhq@gswyhq-PC:~/gswyhq/wiki$ docker-compose -f docker-compose--p1-20180815.yml ps
# 停止容器
# gswyhq@gswyhq-PC:~/gswyhq/wiki$ docker-compose -f docker-compose--p1-20180815.yml stop
# 删除容器
# gswyhq@gswyhq-PC:~/gswyhq/wiki$ docker-compose -f docker-compose--p1-20180815.yml rm -v
